// <auto-generated />
using Dekorasyoncunuz.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dekorasyoncunuzz.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dekorasyoncunuz.Models.Dekorasyon", b =>
                {
                    b.Property<int>("Dekorasyon_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dekorasyon_cinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dekorasyon_fiyat")
                        .HasColumnType("int");

                    b.Property<string>("Dekorasyon_isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dekorasyon_marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dekorasyon_id");

                    b.ToTable("Dekorasyonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
